version: '3'

services:

  tdv_scraper:
    image: tdv_scraper:latest
    volumes:
      - $PWD/charts/:/app/charts:z
      - $PWD/browser_data/:/app/browser_data:z
    environment:
      - DATA_OUTPUT_DIR=/app/charts
      - HEADLESS_SELENIUM=$HEADLESS_SELENIUM
    # command: 'bash'

  # tr8tr:
  #   image: tr8tr_dev:latest